name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false

      - name: Install additional tools
        run: |
          conda install flake8 pytest -y

      - name: Run flake8
        run: |
          flake8 .

      - name: Run pytest
        run: |
          pytest